version: "3"

services:
  builder:
    build:
      context: builder
    image: vestio/builder

  nodvestd:
    build:
      context: .
    image: vestio/vest
    command: /opt/vestio/bin/nodvestd.sh --data-dir /opt/vestio/bin/data-dir -e --http-alias=nodvestd:8888 --http-alias=127.0.0.1:8888 --http-alias=localhost:8888
    hostname: nodvestd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - nodvest-data-volume:/opt/vestio/bin/data-dir
    cap_add:
      - IPC_LOCK
    stop_grace_period: 10m

  kvestd:
    image: vestio/vest
    command: /opt/vestio/bin/kvestd --wallet-dir /opt/vestio/bin/data-dir --http-server-address=127.0.0.1:8900 --http-alias=kvestd:8900 --http-alias=localhost:8900
    hostname: kvestd
    links:
      - nodvestd
    volumes:
      - kvestd-data-volume:/opt/vestio/bin/data-dir
    stop_grace_period: 10m

volumes:
  nodvest-data-volume:
    external: true
  kvestd-data-volume:
    external: true
